config/routes.rb
Seater::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'users/seat' => 'users#seat'
  match 'users/seatjs' => 'users#seatjs'
  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :backchannels
  root :to => "backchannels#index"

end

app/models/backchannel.rb
class Backchannel < ActiveRecord::Base
  attr_accessible :name, :msg
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/backchannels_controller.rb
class BackchannelsController < ApplicationController
  def index
    #@backchannels = Backchannel.all(:order => "created_at DESC")
    @backchannels = Backchannel.where("created_at > ?", Time.at(params[:after].to_i + 1)).find(:all, :order => "created_at DESC", :conditions =>["created_at > ?", 180.minutes.ago])
    @backchannel = Backchannel.new
  end

  def new
    @backchannel = Backchannel.new
  end

  def create
    @backchannel = Backchannel.create!(params[:backchannel])
    flash[:notice] = "Comment successfully submitted!"
    respond_to do |format|
      format.html {redirect_to backchannels_url }
      format.js
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]
  
  def index
    @users = User.find(:all, :conditions => ["row < 20"])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.row = 20
    @user.column = 20
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def seat
    @user = current_user
    @user.update_attribute(:row, params[:row])
    @user.update_attribute(:column, params[:column])
    redirect_to root_url, :notice => "Your seat has been updated, new row:"+@user.row.to_s + ", new column:"+@user.column.to_s
  end
 
  def seatjs
    @user = current_user
    @id = current_user.username
    @user.update_attribute(:row, params[:row])
    @user.update_attribute(:column, params[:column])
    flash[:notice] = "Your seat has been updated, new row: "+@user.row.to_s+" new column: " + @user.column.to_s
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backchannels_helper.rb
module BackchannelsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/backchannels/_backchannel.html.erb
<div class="backchannel" data-time="<%= backchannel.created_at.to_i %>">
  <p><span class="name"><%= backchannel.name %></span> : <%= backchannel.msg %> on <%= backchannel.created_at.strftime('%b %d, %Y at %I:%M %p') %></p>
</div>

app/views/backchannels/_message_form.html.erb
<% if logged_in? %>
  <% form_remote_tag(:controller => "backchannels", :action => "create") do %>
    <%= label_tag(:message, "Post a message for everyone") %><br />
    <%= text_area_tag(:message, nil, :size=>

app/views/backchannels/create.js.erb
$("#backchannels").prepend("<%= raw escape_javascript(render(@backchannel)) %>");

app/views/backchannels/index.html.erb
<% title "Classroom Seating by Cesar and Maks" %>

<p style="text-align: center; font-size: 16px;"> Front of the class</p><br />
<table border cellspacing=4 width="100%">
  <% for i in 1..5 %>
    <tr>
      <% for j in 1..9 %>
        <td height="50px">
          <% student = User.where(:row => i, :column => j).first %>
          <% if j==5 %>
            PATHWAY
          <% else %>
            <% if !student.blank? %>
                <% if logged_in? %>
                  <% if student.row == i && student.column == j %>
                    <% if student.row == current_user.row && student.column == current_user.column %>
                      <span class="current"><%= student.username %></span>
                    <% else %>
                      <span class="taken"><%= student.username %></span>
                    <% end %>
                  <% end %>
                <% else %>
                  <span class="taken"><%= student.username %></span><br />
                <% end %>
              <% else %>
                <% if logged_in? %>
                  <%= link_to "Vacant", {:controller => :users, :action => :seatjs, :row => i, :column => j}, :remote => true, :class => "vacant" %>
              <% else %>
                <span style="color: #008800; font-weight: bold;"> Vacant<span /><br/>
              <% end %>
              <% end %>
            <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<br />
<% if logged_in? %>
  <%= link_to "Remove from class", {:controller => :users, :action => :seat, :row => 20, :column => 20} , :remote => true %> <br />
<% end %><br />
<h3>Currently Assigned:</h3>
<div id="userstatus"></div>
<h2>Backchannel (last 3 hours):  </h2>
<div id="backchannels">
  <%= render @backchannels %>
 </div>

<% if logged_in? %>
  <%= form_for Backchannel.new, :remote => true do |f| %>
    <p>Current User : <%= current_user.username %></p>
    <p>
     <%= f.label :msg %><br />
     <%= f.text_area :msg, :rows => 4, :cols => 60 %>
     <%= f.hidden_field :name, { :value => current_user.username } %>
     </p>
     <p><%= f.submit "Add Message" %></p>
   <% end %>
 <% end %>

app/views/backchannels/index.js.erb
$("#backchannels").prepend("<%= raw escape_javascript(render(@backchannels)) %>")

app/views/backchannels/new.html.erb
<% if logged_in? %>
<% title "New Backchannel" %>

<%= form_for @backchannel do |f| %>
  <p>
    <%= f.label :msg %><br />
    <%= f.text_area :msg %>
  </p>
  <p><%= f.submit %></p>
<% end %>


<p><%= link_to "Back to List", backchannels_path %></p>
<% else %>
  <p>Please log in to post a backchannel message!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
    <div id="signin"><p><%= render :partial => "users/login" %></p></div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <div id="classroom">
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
      </div>
      <div id="footer">Classroom Seating web app by Cesar Acosta and Maksim Surguy. May 2011</div>
    </div>
 </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/_login.html.erb
<% if logged_in? %>
  Welcome <%= current_user.username %>! Not you?
  <%= link_to "Log out", logout_path %>
<% else %>
  <%= link_to "Sign up", signup_path %> or
  <%= link_to "log in", login_path %>.

<% end %>

app/views/users/_user.html.erb
<div class="user">
  <p><span class="name"> <%= user.username %></span>  position( row: <%= user.row %> , column: <%= user.column %>)</p>
</div>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/index.js.erb
$("#userstatus").empty();
$("#userstatus").append("<%= raw escape_javascript(render(@users)) %>");

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/seatjs.js.erb
$("#flash_notice").remove()
$("#classroom").before('<div id="flash_notice"><%= escape_javascript(flash.delete(:notice)) %></div>');
var currrow = $("table tr td:contains('<%= @id %>')").index();
var currcol = $("table tr:contains('<%= @id %>')").index();
//$("table tr td span").removeClass("current");
$("table tr td span.current").replaceWith("<a href='/users/seatjs?column="+(currcol+1)+"&amp;row="+(currrow+1)+"' data-remote='true'>Vacant</a>");
$("table tr:nth-child(<%= @user.row %>) td:nth-child(<%= @user.column %>)").eq(0).html("<span class='current'><%= @id %></span>");